### ISSUE TITLE
specify source for downloaded "IPHIS_REPORT.csv"

### ISSUE THREAD

**Issue by titaniumbones** [mishra-lab/covid-r#1]
are you able to specify a public URL from which the data source file `IPHIS_REPORT.csv` is derived? My best guess is 
https://data.ontario.ca/dataset/f4f86e54-872d-43f8-8a86-3892fd3cb5e6/resource/8a88fe6d-d8fb-41a3-9d04-f0550a44999f/download/daily_change_in_cases_by_phu.csv

but when using that file I get the following initial error:

```
$ make iphis-min
Rscript Re/data/iphis-min.r
Error in `[.data.frame`(X, , cols) : undefined columns selected
Calls: save.data ... eval -> write.table -> is.data.frame -> [ -> [.data.frame
Execution halted
make: *** [Makefile:5: iphis-min] Error 1
```

Thank you!

**Comment by jessexknight** [comment]
Sorry, those data are private, individual-level data that we had access to through the [Modelling Consensus Table](https://covid19-sciencetable.ca/our-partners/).
